```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(rpart)
library(rpart.plot)
library(rsample) 
library(randomForest)
library(lubridate)
library(modelr)
library(gbm)
library(caret)
library(gamlr)

shoe_final = read.csv("data/shoe_final.csv")

```


```{r, cache=TRUE, echo=FALSE}
premium_data = shoe_final %>%
  mutate(premium = (sale_price - retail_price)/retail_price) %>%
  mutate_if(is.character, as.factor)

# split data into training and testing
set.seed(349385)
premium_split = initial_split(premium_data, prop=0.8)
premium_train = training(premium_split)
premium_test  = testing(premium_split)

# a single tree
premium_tree = rpart(premium ~ brand + sneaker_name + shoe_size + buyer_region + Year_month  + primary_color + secondary_color + Material, data = premium_train,
                    control = rpart.control(cp = 0.02, minsplit=300), maxdepth = 4)

#rpart.plot(premium_tree, digits=-5, type=4, extra=1)

# forest 
premium_forest = randomForest(premium ~ brand + sneaker_name + shoe_size + buyer_region + Year_month  + primary_color + secondary_color + Material, data=premium_train, control = rpart.control(cp = 0.002), ntrees = 300, importance=TRUE, na.action = na.omit)


# variable importance measures
vi = varImpPlot(premium_forest, type=1)

# # forest pd plots
partialPlot(premium_forest, premium_test, 'Year_month', las=1)
partialPlot(premium_forest, premium_test, 'shoe_size', las=1)
partialPlot(premium_forest, premium_test, 'sneaker_name', las=1)

# finished model building: compare RMSE
rmse_premium_tree = rmse(premium_tree, premium_test)
rmse_premium_forest = rmse(premium_forest, premium_test)

rmse_premium_tree
rmse_premium_forest
```