---
title: "Shoe try"
author: "Blake Lin"
date: "4/21/2022"
output: html_document
---

## Discussion Note
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
shoe_data <- read.csv("~/Documents/MA Courses/Data Mining/R_FinalProject/shoe_data.txt")
monthly_retail <- read_csv("monthly_retail.csv")
sp_index <- read_csv("data/s&p_index.csv")

library(tidyverse)
library(lubridate)

#Demographic
  # state population
  # state income

#Market Trend
  # ETF price - consumer good/ S&P 500
  # retail sales trend - US Census Bureau

#Popularity
  #Team performance
  #google search trend
  #social media
  #Kayne's song on chart 

#Product
  # Shoe dimension
  # material






```


### Data Cleaning 
```{r data cleaning, echo=FALSE}

shoe_data = shoe_data %>% 
  mutate(time_stamp=mdy(shoe_data$order_date), .before=order_date)

monthly_retail=monthly_retail %>% 
  mutate(time_stamp=mdy(Period))
monthly_retail = monthly_retail[ ,-(1)]

sp_index = sp_index%>% 
  mutate(time_stamp=mdy(date))
sp_index = sp_index[ ,-(3:10)]
sp_index = sp_index[ ,-(1)]





```



```{r}
# some dates have completely missing weather data
# Keep the load data for dates when we have weather data
mysub = which(ymd_hms(load_data$Time) %in% ymd_hms(rownames(temperature_impute)))
load_data = load_data[mysub,]

# De-duplicate the weather data by merging on first match of date in the load data
temp_ind = match(ymd_hms(load_data$Time), ymd_hms(rownames(temperature_impute)))
temperature_impute = temperature_impute[temp_ind,]

# Take the time stamps from the load data
time_stamp = ymd_hms(load_data$Time)

# Verify that the time stamps match row by row across the two data frames
all(time_stamp ==  ymd_hms(rownames(temperature_impute)))

# a lot of these station names are in Mexico or the Gulf
# and we don't have temperature data on them
station_data = subset(station_data, state != 'MX')

# Make a map.
# First, project project the lon, lat coordinates
# to the same coordinate system used by usmap
station_map = station_data %>%
  select(lon, lat) %>%
  usmap_transform 

head(station_map)

# now merge these coordinates station name
station_data = station_data %>% rownames_to_column('station')
station_data = merge(station_data, station_map, by=c('lat', 'lon'))
head(station_data)

# plot the coordinates of the weather stations
plot_usmap(include = c("TX", "LA", "OK", "NM", "AR")) + 
  geom_point(data=station_data, aes(x=lon.1, y=lat.1))

```




### Reference 
##### S&P Retail Select Industry Index
https://www.spglobal.com/spdji/en/indices/equity/sp-retail-select-industry-index/#overview

##### US Census Bureau
https://www.census.gov/retail/marts/historic_releases.html

