library(tidyverse)


df = read.csv("/Users/jaymegerring/Downloads/GitHub/R_FinalProject/shoe_data.txt", header = TRUE, dec = ".")
df$order_date = as.Date(df$order_date,"%m/%d/%y")
df %>% add_column(year = NA)
df$year = year
df %>% add_column(State_pop_year = NA)


  df$State_pop_year = case_when(df$buyer_region == "California" & df$year == "2017" ~ "39.36",
                                    df$buyer_region == "California" & df$year == "2018" ~ "39.46",
                                    df$buyer_region == "California" & df$year == "2019" ~ "39.51",
                                    df$buyer_region == "Alabama" & df$year == "2017" ~ "4.874",
                                    df$buyer_region == "Alabama" & df$year == "2018" ~ "4.888",
                                    df$buyer_region == "Alabama" & df$year == "2019" ~ "4.903",
                                    df$buyer_region == "Arkansas" & df$year == "2017" ~ "3.001",
                                    df$buyer_region == "Arkansas" & df$year == "2018" ~ "3.01",
                                    df$buyer_region == "Arkansas" & df$year == "2019" ~ "3.018",
                                    df$buyer_region == "Arizona" & df$year == "2017" ~ "7.044",
                                    df$buyer_region == "Arizona" & df$year == "2018" ~ "7.158",
                                    df$buyer_region == "Arizona" & df$year == "2019" ~ "7.279",
                                    df$buyer_region == "Alaska" & df$year == "2017" ~ ".739700",
                                    df$buyer_region == "Alaska" & df$year == "2018" ~ ".735139",
                                    df$buyer_region == "Alaska" & df$year == "2019" ~ ".731545",
                                    df$buyer_region == "Colorado" & df$year == "2017" ~ "5.612",
                                    df$buyer_region == "Colorado" & df$year == "2018" ~ "5.691",
                                    df$buyer_region == "Colorado" & df$year == "2019" ~ "5.759",
                                    df$buyer_region == "Connecticut" & df$year == "2017" ~ "3.573",
                                    df$buyer_region == "Connecticut" & df$year == "2018" ~ "3.572",
                                    df$buyer_region == "Connecticut" & df$year == "2019" ~ "3.565",
                                    df$buyer_region == "Delaware" & df$year == "2017" ~ ".956823",
                                    df$buyer_region == "Delaware" & df$year == "2018" ~ ".965479",
                                    df$buyer_region == "Delaware" & df$year == "2019" ~ ".973764",
                                    df$buyer_region == "District of Columbia" & df$year == "2017" ~ ".672391",
                                    df$buyer_region == "District of Columbia" & df$year == "2018" ~ ".684498",
                                    df$buyer_region == "District of Columbia" & df$year == "2019" ~ ".692683",
                                    df$buyer_region == "Florida" & df$year == "2017" ~ "20.96",
                                    df$buyer_region == "Florida" & df$year == "2018" ~ "21.24",
                                    df$buyer_region == "Florida" & df$year == "2019" ~ "21.48",
                                    df$buyer_region == "Georgia" & df$year == "2017" ~ "10.41",
                                    df$buyer_region == "Georgia" & df$year == "2018" ~ "10.51",
                                    df$buyer_region == "Georgia" & df$year == "2019" ~ "10.62",
                                    df$buyer_region == "Hawaii" & df$year == "2017" ~ "1.424",
                                    df$buyer_region == "Hawaii" & df$year == "2018" ~ "1.421",
                                    df$buyer_region == "Hawaii" & df$year == "2019" ~ "1.416",
                                    df$buyer_region == "Idaho" & df$year == "2017" ~ "1.718",
                                    df$buyer_region == "Idaho" & df$year == "2018" ~ "1.751",
                                    df$buyer_region == "Idaho" & df$year == "2019" ~ "1.787",
                                    df$buyer_region == "Illinois" & df$year == "2017" ~ "12.78",
                                    df$buyer_region == "Illinois" & df$year == "2018" ~ "12.72",
                                    df$buyer_region == "Illinois" & df$year == "2019" ~ "12.67",
                                    df$buyer_region == "Indiana" & df$year == "2017" ~ "6.658",
                                    df$buyer_region == "Indiana" & df$year == "2018" ~ "6.695",
                                    df$buyer_region == "Indiana" & df$year == "2019" ~ "6.732",
                                    df$buyer_region == "Iowa" & df$year == "2017" ~ "3.142",
                                    df$buyer_region == "Iowa" & df$year == "2018" ~ "3.149",
                                    df$buyer_region == "Iowa" & df$year == "2019" ~ "3.155",
                                    df$buyer_region == "Kansas" & df$year == "2017" ~ "2.909",
                                    df$buyer_region == "Kansas" & df$year == "2018" ~ "2.911",
                                    df$buyer_region == "Kansas" & df$year == "2019" ~ "2.913",
                                    df$buyer_region == "Kentucky" & df$year == "2017" ~ "4.452",
                                    df$buyer_region == "Kentucky" & df$year == "2018" ~ "4.461",
                                    df$buyer_region == "Kentucky" & df$year == "2019" ~ "4.468",
                                    df$buyer_region == "Louisiana" & df$year == "2017" ~ "4.671",
                                    df$buyer_region == "Louisiana" & df$year == "2018" ~ "4.66",
                                    df$buyer_region == "Louisiana" & df$year == "2019" ~ "4.649",
                                    df$buyer_region == "Maine" & df$year == "2017" ~ "1.335",
                                    df$buyer_region == "Maine" & df$year == "2018" ~ "1.339",
                                    df$buyer_region == "Maine" & df$year == "2019" ~ "1.344",
                                    df$buyer_region == "Maryland" & df$year == "2017" ~ "6.024",
                                    df$buyer_region == "Maryland" & df$year == "2018" ~ "6.036",
                                    df$buyer_region == "Maryland" & df$year == "2019" ~ "6.046",
                                    df$buyer_region == "Massachusetts" & df$year == "2017" ~ "6.86",
                                    df$buyer_region == "Massachusetts" & df$year == "2018" ~ "6.883",
                                    df$buyer_region == "Massachusetts" & df$year == "2019" ~ "6.893",
                                    df$buyer_region == "Michigan" & df$year == "2017" ~ "9.973",
                                    df$buyer_region == "Michigan" & df$year == "2018" ~ "9.984",
                                    df$buyer_region == "Michigan" & df$year == "2019" ~ "9.987",
                                    df$buyer_region == "Minnesota" & df$year == "2017" ~ "5.566",
                                    df$buyer_region == "Minnesota" & df$year == "2018" ~ "5.606",
                                    df$buyer_region == "Minnesota" & df$year == "2019" ~ "5.64",
                                    df$buyer_region == "Mississippi" & df$year == "2017" ~ "2.989",
                                    df$buyer_region == "Mississippi" & df$year == "2018" ~ "2.981",
                                    df$buyer_region == "Mississippi" & df$year == "2019" ~ "2.976",
                                    df$buyer_region == "Missouri" & df$year == "2017" ~ "6.107",
                                    df$buyer_region == "Missouri" & df$year == "2018" ~ "6.122",
                                    df$buyer_region == "Missouri" & df$year == "2019" ~ "6.137",
                                    df$buyer_region == "Montana" & df$year == "2017" ~ "1.052",
                                    df$buyer_region == "Montana" & df$year == "2018" ~ "1.061",
                                    df$buyer_region == "Montana" & df$year == "2019" ~ "1.069",
                                    df$buyer_region == "Nebraska" & df$year == "2017" ~ "1.916",
                                    df$buyer_region == "Nebraska" & df$year == "2018" ~ "1.926",
                                    df$buyer_region == "Nebraska" & df$year == "2019" ~ "1.934",
                                    df$buyer_region == "Nevada" & df$year == "2017" ~ "2.97",
                                    df$buyer_region == "Nevada" & df$year == "2018" ~ "3.027",
                                    df$buyer_region == "Nevada" & df$year == "2019" ~ "3.08",
                                    df$buyer_region == "New Hampshire" & df$year == "2017" ~ "1.349",
                                    df$buyer_region == "New Hampshire" & df$year == "2018" ~ "1.353",
                                    df$buyer_region == "New Hampshire" & df$year == "2019" ~ "1.36",
                                    df$buyer_region == "New Jersey" & df$year == "2017" ~ "8.886",
                                    df$buyer_region == "New Jersey" & df$year == "2018" ~ "8.886",
                                    df$buyer_region == "New Jersey" & df$year == "2019" ~ "8.882",
                                    df$buyer_region == "New Mexico" & df$year == "2017" ~ "2.092",
                                    df$buyer_region == "New Mexico" & df$year == "2018" ~ "2.093",
                                    df$buyer_region == "New Mexico" & df$year == "2019" ~ "2.097",
                                    df$buyer_region == "New York" & df$year == "2017" ~ "19.59",
                                    df$buyer_region == "New York" & df$year == "2018" ~ "19.53",
                                    df$buyer_region == "New York" & df$year == "2019" ~ "19.45",
                                    df$buyer_region == "North Carolina" & df$year == "2017" ~ "10.27",
                                    df$buyer_region == "North Carolina" & df$year == "2018" ~ "10.38",
                                    df$buyer_region == "North Carolina" & df$year == "2019" ~ "10.49",
                                    df$buyer_region == "North Dakota" & df$year == "2017" ~ ".754942",
                                    df$buyer_region == "North Dakota" & df$year == "2018" ~ ".758080",
                                    df$buyer_region == "North Dakota" & df$year == "2019" ~ ".762062",
                                    df$buyer_region == "Ohio" & df$year == "2017" ~ "11.66",
                                    df$buyer_region == "Ohio" & df$year == "2018" ~ "11.68",
                                    df$buyer_region == "Ohio" & df$year == "2019" ~ "11.69",
                                    df$buyer_region == "Oklahoma" & df$year == "2017" ~ "3.931",
                                    df$buyer_region == "Oklahoma" & df$year == "2018" ~ "3.94",
                                    df$buyer_region == "Oklahoma" & df$year == "2019" ~ "3.957",
                                    df$buyer_region == "Oregon" & df$year == "2017" ~ "4.144",
                                    df$buyer_region == "Oregon" & df$year == "2018" ~ "4.182",
                                    df$buyer_region == "Oregon" & df$year == "2019" ~ "4.218",
                                    df$buyer_region == "Pennsylvania" & df$year == "2017" ~ "12.79",
                                    df$buyer_region == "Pennsylvania" & df$year == "2018" ~ "12.8",
                                    df$buyer_region == "Pennsylvania" & df$year == "2019" ~ "12.8",
                                    df$buyer_region == "Rhode Island" & df$year == "2017" ~ "1.056",
                                    df$buyer_region == "Rhode Island" & df$year == "2018" ~ "1.058",
                                    df$buyer_region == "Rhode Island" & df$year == "2019" ~ "1.059",
                                    df$buyer_region == "South Carolina" & df$year == "2017" ~ "5.021",
                                    df$buyer_region == "South Carolina" & df$year == "2018" ~ "5.084",
                                    df$buyer_region == "South Carolina" & df$year == "2019" ~ "5.149",
                                    df$buyer_region == "South Dakota" & df$year == "2017" ~ ".872868",
                                    df$buyer_region == "South Dakota" & df$year == "2018" ~ ".878698",
                                    df$buyer_region == "South Dakota" & df$year == "2019" ~ ".884659",
                                    df$buyer_region == "Tennessee" & df$year == "2017" ~ "6.709",
                                    df$buyer_region == "Tennessee" & df$year == "2018" ~ "6.772",
                                    df$buyer_region == "Tennessee" & df$year == "2019" ~ "6.829",
                                    df$buyer_region == "Texas" & df$year == "2017" ~ "28.3",
                                    df$buyer_region == "Texas" & df$year == "2018" ~ "28.63",
                                    df$buyer_region == "Texas" & df$year == "2019" ~ "29",
                                    df$buyer_region == "Utah" & df$year == "2017" ~ "3.101",
                                    df$buyer_region == "Utah" & df$year == "2018" ~ "3.154",
                                    df$buyer_region == "Utah" & df$year == "2019" ~ "3.206",
                                    df$buyer_region == "Vermont" & df$year == "2017" ~ ".624344",
                                    df$buyer_region == "Vermont" & df$year == "2018" ~ ".624358",
                                    df$buyer_region == "Vermont" & df$year == "2019" ~ ".6239890",
                                    df$buyer_region == "Virginia" & df$year == "2017" ~ "8.464",
                                    df$buyer_region == "Virginia" & df$year == "2018" ~ "8.501",
                                    df$buyer_region == "Virginia" & df$year == "2019" ~ "8.536",
                                    df$buyer_region == "Washington" & df$year == "2017" ~ "7.423",
                                    df$buyer_region == "Washington" & df$year == "2018" ~ "7.524",
                                    df$buyer_region == "Washington" & df$year == "2019" ~ "7.615",
                                    df$buyer_region == "West Virginia" & df$year == "2017" ~ "1.817",
                                    df$buyer_region == "West Virginia" & df$year == "2018" ~ "1.804",
                                    df$buyer_region == "West Virginia" & df$year == "2019" ~ "1.792",
                                    df$buyer_region == "Wisconsin" & df$year == "2017" ~ "5.79",
                                    df$buyer_region == "Wisconsin" & df$year == "2018" ~ "5.807",
                                    df$buyer_region == "Wisconsin" & df$year == "2019" ~ "5.822",
                                    df$buyer_region == "Wyoming" & df$year == "2017" ~ ".578931",
                                    df$buyer_region == "Wyoming" & df$year == "2018" ~ ".577601",
                                    df$buyer_region == "Wyoming" & df$year == "2019" ~ ".578759")
  
  df %>% add_column(state_GDP = NA)
  
  df$state_GDP = case_when(df$buyer_region == "California" & df$year == "2017" ~ "50,350",
                                df$buyer_region == "California" & df$year == "2018" ~ "52,560",
                                df$buyer_region == "California" & df$year == "2019" ~ "54,936",
                                df$buyer_region == "Alabama" & df$year == "2017" ~ "36,447",
                                df$buyer_region == "Alabama" & df$year == "2018" ~ "37,914",
                                df$buyer_region == "Alabama" & df$year == "2019" ~ "39,199",
                                df$buyer_region == "Arkansas" & df$year == "2017" ~ "37,989",
                                df$buyer_region == "Arkansas" & df$year == "2018" ~ "39,768",
                                df$buyer_region == "Arkansas" & df$year == "2019" ~ "40,901",
                                df$buyer_region == "Arizona" & df$year == "2017" ~ "38,851",
                                df$buyer_region == "Arizona" & df$year == "2018" ~ "40,733",
                                df$buyer_region == "Arizona" & df$year == "2019" ~ "42,454",
                                df$buyer_region == "Alaska" & df$year == "2017" ~ "52,701",
                                df$buyer_region == "Alaska" & df$year == "2018" ~ "55,421",
                                df$buyer_region == "Alaska" & df$year == "2019" ~ "57,020",
                                df$buyer_region == "Colorado" & df$year == "2017" ~ "48,307",
                                df$buyer_region == "Colorado" & df$year == "2018" ~ "51,395",
                                df$buyer_region == "Colorado" & df$year == "2019" ~ "53,636",
                                df$buyer_region == "Connecticut" & df$year == "2017" ~ "59,252",
                                df$buyer_region == "Connecticut" & df$year == "2018" ~ "62,207",
                                df$buyer_region == "Connecticut" & df$year == "2019" ~ "63,459",
                                df$buyer_region == "Delaware" & df$year == "2017" ~ "44,699",
                                df$buyer_region == "Delaware" & df$year == "2018" ~ "46,865",
                                df$buyer_region == "Delaware" & df$year == "2019" ~ "47,210",
                                df$buyer_region == "District of Columbia" & df$year == "2017" ~ "67,942",
                                df$buyer_region == "District of Columbia" & df$year == "2018" ~ "69,852",
                                df$buyer_region == "District of Columbia" & df$year == "2019" ~ "69,911",
                                df$buyer_region == "Florida" & df$year == "2017" ~ "43,230",
                                df$buyer_region == "Florida" & df$year == "2018" ~ "46,054",
                                df$buyer_region == "Florida" & df$year == "2019" ~ "47,751",
                                df$buyer_region == "Georgia" & df$year == "2017" ~ "39,937",
                                df$buyer_region == "Georgia" & df$year == "2018" ~ "41,855",
                                df$buyer_region == "Georgia" & df$year == "2019" ~ "43,461",
                                df$buyer_region == "Hawaii" & df$year == "2017" ~ "45,419",
                                df$buyer_region == "Hawaii" & df$year == "2018" ~ "46,604",
                                df$buyer_region == "Hawaii" & df$year == "2019" ~ "47,968",
                                df$buyer_region == "Idaho" & df$year == "2017" ~ "37,353",
                                df$buyer_region == "Idaho" & df$year == "2018" ~ "39,162",
                                df$buyer_region == "Idaho" & df$year == "2019" ~ "40,862",
                                df$buyer_region == "Illinois" & df$year == "2017" ~ "47,152",
                                df$buyer_region == "Illinois" & df$year == "2018" ~ "49,711",
                                df$buyer_region == "Illinois" & df$year == "2019" ~ "50,896",
                                df$buyer_region == "Indiana" & df$year == "2017" ~ "40,611",
                                df$buyer_region == "Indiana" & df$year == "2018" ~ "42,710",
                                df$buyer_region == "Indiana" & df$year == "2019" ~ "43,912",
                                df$buyer_region == "Iowa" & df$year == "2017" ~ "42,306",
                                df$buyer_region == "Iowa" & df$year == "2018" ~ "44,327",
                                df$buyer_region == "Iowa" & df$year == "2019" ~ "44,952",
                                df$buyer_region == "Kansas" & df$year == "2017" ~ "43,796",
                                df$buyer_region == "Kansas" & df$year == "2018" ~ "45,633",
                                df$buyer_region == "Kansas" & df$year == "2019" ~ "47,311",
                                df$buyer_region == "Kentucky" & df$year == "2017" ~ "36,515",
                                df$buyer_region == "Kentucky" & df$year == "2018" ~ "37,757",
                                df$buyer_region == "Kentucky" & df$year == "2019" ~ "39,088",
                                df$buyer_region == "Louisiana" & df$year == "2017" ~ "40,174",
                                df$buyer_region == "Louisiana" & df$year == "2018" ~ "42,204",
                                df$buyer_region == "Louisiana" & df$year == "2019" ~ "43,421",
                                df$buyer_region == "Maine" & df$year == "2017" ~ "41,657",
                                df$buyer_region == "Maine" & df$year == "2018" ~ "43,502",
                                df$buyer_region == "Maine" & df$year == "2019" ~ "44,896",
                                df$buyer_region == "Maryland" & df$year == "2017" ~ "51,249",
                                df$buyer_region == "Maryland" & df$year == "2018" ~ "52,597",
                                df$buyer_region == "Maryland" & df$year == "2019" ~ "53,258",
                                df$buyer_region == "Massachusetts" & df$year == "2017" ~ "56,361",
                                df$buyer_region == "Massachusetts" & df$year == "2018" ~ "59,024",
                                df$buyer_region == "Massachusetts" & df$year == "2019" ~ "60,990",
                                df$buyer_region == "Michigan" & df$year == "2017" ~ "40,480",
                                df$buyer_region == "Michigan" & df$year == "2018" ~ "42,179",
                                df$buyer_region == "Michigan" & df$year == "2019" ~ "43,390",
                                df$buyer_region == "Minnesota" & df$year == "2017" ~ "47,009",
                                df$buyer_region == "Minnesota" & df$year == "2018" ~ "49,223",
                                df$buyer_region == "Minnesota" & df$year == "2019" ~ "50,249",
                                df$buyer_region == "Mississippi" & df$year == "2017" ~ "33,969",
                                df$buyer_region == "Mississippi" & df$year == "2018" ~ "35,080",
                                df$buyer_region == "Mississippi" & df$year == "2019" ~ "36,143",
                                df$buyer_region == "Missouri" & df$year == "2017" ~ "40,514",
                                df$buyer_region == "Missouri" & df$year == "2018" ~ "42,352",
                                df$buyer_region == "Missouri" & df$year == "2019" ~ "43,782",
                                df$buyer_region == "Montana" & df$year == "2017" ~ "41,263",
                                df$buyer_region == "Montana" & df$year == "2018" ~ "42,962",
                                df$buyer_region == "Montana" & df$year == "2019" ~ "44,702",
                                df$buyer_region == "Nebraska" & df$year == "2017" ~ "45,090",
                                df$buyer_region == "Nebraska" & df$year == "2018" ~ "46,977",
                                df$buyer_region == "Nebraska" & df$year == "2019" ~ "48,046",
                                df$buyer_region == "Nevada" & df$year == "2017" ~ "42,587",
                                df$buyer_region == "Nevada" & df$year == "2018" ~ "44,583",
                                df$buyer_region == "Nevada" & df$year == "2019" ~ "46,411",
                                df$buyer_region == "New Hampshire" & df$year == "2017" ~ "52,311",
                                df$buyer_region == "New Hampshire" & df$year == "2018" ~ "54,915",
                                df$buyer_region == "New Hampshire" & df$year == "2019" ~ "56,942",
                                df$buyer_region == "New Jersey" & df$year == "2017" ~ "53,825",
                                df$buyer_region == "New Jersey" & df$year == "2018" ~ "56,164",
                                df$buyer_region == "New Jersey" & df$year == "2019" ~ "57,758",
                                df$buyer_region == "New Mexico" & df$year == "2017" ~ "35,981",
                                df$buyer_region == "New Mexico" & df$year == "2018" ~ "37,690",
                                df$buyer_region == "New Mexico" & df$year == "2019" ~ "39,248",
                                df$buyer_region == "New York" & df$year == "2017" ~ "52,809",
                                df$buyer_region == "New York" & df$year == "2018" ~ "54,525",
                                df$buyer_region == "New York" & df$year == "2019" ~ "56,070",
                                df$buyer_region == "North Carolina" & df$year == "2017" ~ "39,532",
                                df$buyer_region == "North Carolina" & df$year == "2018" ~ "41,237",
                                df$buyer_region == "North Carolina" & df$year == "2019" ~ "42,948",
                                df$buyer_region == "North Dakota" & df$year == "2017" ~ "47,411",
                                df$buyer_region == "North Dakota" & df$year == "2018" ~ "50,593",
                                df$buyer_region == "North Dakota" & df$year == "2019" ~ "52,024",
                                df$buyer_region == "Ohio" & df$year == "2017" ~ "41,691",
                                df$buyer_region == "Ohio" & df$year == "2018" ~ "43,474",
                                df$buyer_region == "Ohio" & df$year == "2019" ~ "44,559",
                                df$buyer_region == "Oklahoma" & df$year == "2017" ~ "40,344",
                                df$buyer_region == "Oklahoma" & df$year == "2018" ~ "42,433",
                                df$buyer_region == "Oklahoma" & df$year == "2019" ~ "44,256",
                                df$buyer_region == "Oregon" & df$year == "2017" ~ "41,678",
                                df$buyer_region == "Oregon" & df$year == "2018" ~ "44,091",
                                df$buyer_region == "Oregon" & df$year == "2019" ~ "45,661",
                                df$buyer_region == "Pennsylvania" & df$year == "2017" ~ "46,404",
                                df$buyer_region == "Pennsylvania" & df$year == "2018" ~ "49,120",
                                df$buyer_region == "Pennsylvania" & df$year == "2019" ~ "50,316",
                                df$buyer_region == "Rhode Island" & df$year == "2017" ~ "45,116",
                                df$buyer_region == "Rhode Island" & df$year == "2018" ~ "46,775",
                                df$buyer_region == "Rhode Island" & df$year == "2019" ~ "48,649",
                                df$buyer_region == "South Carolina" & df$year == "2017" ~ "38,508",
                                df$buyer_region == "South Carolina" & df$year == "2018" ~ "40,011",
                                df$buyer_region == "South Carolina" & df$year == "2019" ~ "41,559",
                                df$buyer_region == "South Dakota" & df$year == "2017" ~ "46,141",
                                df$buyer_region == "South Dakota" & df$year == "2018" ~ "48,533",
                                df$buyer_region == "South Dakota" & df$year == "2019" ~ "50,745",
                                df$buyer_region == "Tennessee" & df$year == "2017" ~ "41,164",
                                df$buyer_region == "Tennessee" & df$year == "2018" ~ "43,274",
                                df$buyer_region == "Tennessee" & df$year == "2019" ~ "44,874",
                                df$buyer_region == "Texas" & df$year == "2017" ~ "44,330",
                                df$buyer_region == "Texas" & df$year == "2018" ~ "47,404",
                                df$buyer_region == "Texas" & df$year == "2019" ~ "48,705",
                                df$buyer_region == "Utah" & df$year == "2017" ~ "38,555",
                                df$buyer_region == "Utah" & df$year == "2018" ~ "40,920",
                                df$buyer_region == "Utah" & df$year == "2019" ~ "43,380",
                                df$buyer_region == "Vermont" & df$year == "2017" ~ "45,432",
                                df$buyer_region == "Vermont" & df$year == "2018" ~ "46,960",
                                df$buyer_region == "Vermont" & df$year == "2019" ~ "48,347",
                                df$buyer_region == "Virginia" & df$year == "2017" ~ "47,971",
                                df$buyer_region == "Virginia" & df$year == "2018" ~ "49,666",
                                df$buyer_region == "Virginia" & df$year == "2019" ~ "50,909",
                                df$buyer_region == "Washington" & df$year == "2017" ~ "50,903",
                                df$buyer_region == "Washington" & df$year == "2018" ~ "53,765",
                                df$buyer_region == "Washington" & df$year == "2019" ~ "56,150",
                                df$buyer_region == "West Virginia" & df$year == "2017" ~ "35,589",
                                df$buyer_region == "West Virginia" & df$year == "2018" ~ "37,742",
                                df$buyer_region == "West Virginia" & df$year == "2019" ~ "38,562",
                                df$buyer_region == "Wisconsin" & df$year == "2017" ~ "43,184",
                                df$buyer_region == "Wisconsin" & df$year == "2018" ~ "45,245",
                                df$buyer_region == "Wisconsin" & df$year == "2019" ~ "46,456",
                                df$buyer_region == "Wyoming" & df$year == "2017" ~ "51,351",
                                df$buyer_region == "Wyoming" & df$year == "2018" ~ "54,762",
                                df$buyer_region == "Wyoming" & df$year == "2019" ~ "55,718")


         